@TendersData.Api_HostAddress = http://localhost:5216

### Get Tender by ID
GET {{TendersData.Api_HostAddress}}/api/tenders/1
Accept: application/json

###

### Get Tender by ID - Example 2
GET {{TendersData.Api_HostAddress}}/api/tenders/100
Accept: application/json

###

